In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
import datetime

import ta, pickle, json, time

In [2]:
data = pd.read_csv("1-Data creation/data_creation.csv")

In [80]:
len(data)

sma_20_50             1.000000
sma_20_100            1.000000
sma_50_100            1.000000
ema_20_50             1.000000
ema_20_100            1.000000
ema_50_100            1.000000
vwap_20_50            1.000000
vwap_20_100           1.000000
vwap_50_100           1.000000
awesome_oscillator    1.000000
ppo                   1.000000
ppo_hist              1.000000
pvo                   1.000000
pvo_hist              1.000000
rsi_close             1.000000
rsi_high              1.000000
rsi_low               1.000000
srsi                  1.000000
srsi_d                1.000000
srsi_k                1.000000
stoch                 1.000000
stoch_signal          1.000000
tsi                   0.986405
ultimate_o            0.980735
will                  1.000000
cmf                   0.980623
em                    1.000000
sem                   1.000000
mfi                   1.000000
bbh                   1.000000
bbl                   1.000000
bbm                   1.000000
dch                   0.000000
dcl                   0.000000
dcm                   1.000000
kch                   1.000000
kcl                   1.000000
kcm                   1.000000
adx                   0.745490
adx_neg               0.864823
adx_pos               0.993283
aroon_d               1.000000
aroon_u               1.000000
aroon_i               0.980000
cci                   1.000000
dpo                   1.000000
kst                   1.000000
kst_diff              1.000000
kst_sig               1.000000
macd                  1.000000
macd_d                1.000000
macd_s                1.000000
psar_d                1.000000
psar_u                1.000000
stc                   1.000000
trix                  1.000000
vortex                1.000000
dtype: float64

In [81]:
data.min()

sma_20_50             0.000000e+00
sma_20_100            0.000000e+00
sma_50_100            0.000000e+00
ema_20_50             0.000000e+00
ema_20_100            0.000000e+00
ema_50_100            0.000000e+00
vwap_20_50            0.000000e+00
vwap_20_100           0.000000e+00
vwap_50_100           0.000000e+00
awesome_oscillator    0.000000e+00
ppo                   0.000000e+00
ppo_hist              0.000000e+00
pvo                   0.000000e+00
pvo_hist              0.000000e+00
rsi_close             0.000000e+00
rsi_high              0.000000e+00
rsi_low               0.000000e+00
srsi                  0.000000e+00
srsi_d                0.000000e+00
srsi_k                0.000000e+00
stoch                 0.000000e+00
stoch_signal          0.000000e+00
tsi                   0.000000e+00
ultimate_o            0.000000e+00
will                 -1.421085e-16
cmf                   1.452989e-01
em                    0.000000e+00
sem                   0.000000e+00
mfi                   0.000000e+00
bbh                   0.000000e+00
bbl                   0.000000e+00
bbm                   0.000000e+00
dch                   0.000000e+00
dcl                   0.000000e+00
dcm                   0.000000e+00
kch                   0.000000e+00
kcl                   0.000000e+00
kcm                   0.000000e+00
adx                   0.000000e+00
adx_neg               0.000000e+00
adx_pos               0.000000e+00
aroon_d               4.000000e-02
aroon_u               4.000000e-02
aroon_i               2.000000e-02
cci                   0.000000e+00
dpo                   0.000000e+00
kst                   0.000000e+00
kst_diff              0.000000e+00
kst_sig               0.000000e+00
macd                  0.000000e+00
macd_d                0.000000e+00
macd_s                0.000000e+00
psar_d                0.000000e+00
psar_u                0.000000e+00
stc                   0.000000e+00
trix                  0.000000e+00
vortex                0.000000e+00
dtype: float64

In [39]:
data < 1

,sma_20_50,sma_20_100,sma_50_100,ema_20_50,ema_20_100,ema_50_100,vwap_20_50,vwap_20_100,vwap_50_100,awesome_oscillator,...,kst_diff,kst_sig,macd,macd_d,macd_s,psar_d,psar_u,stc,trix,vortex
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,False,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,False,False,False,True,True,True,True,...,False,True,False,False,False,False,True,True,False,False
3,True,True,True,False,False,False,True,True,True,True,...,False,True,False,False,False,True,False,True,False,False
4,True,True,True,False,False,False,True,True,True,True,...,False,True,False,False,False,True,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524643,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,True,True,True,False,True
524644,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,True,True,True,False,True
524645,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,True,True,True,False,True
524646,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,False,True,True,True,False,True
524647,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,False,True,True,True,False,True

In [28]:
data[["sma_20_50"]]

        sma_20_50
0              -1
1              -1
2              -1
3              -1
4              -1
...           ...
524643          1
524644          1
524645          1
524646          1
524647          1

[524648 rows x 1 columns]

In [40]:
data = pd.DataFrame()

In [41]:
df = pd.read_csv("data 1 year/BTCUSDT.csv").drop(
    ["bear", "bull", "ema20", "ema50", "ema100"], axis=1
)
df

,timestamp,open,high,low,close,volume
0,2020-07-11 22:17:00,9226.00,9226.00,9223.30,9224.20,8.967077
1,2020-07-11 22:18:00,9224.21,9225.00,9223.02,9223.80,11.122493
2,2020-07-11 22:19:00,9223.78,9226.46,9223.05,9225.99,14.178658
3,2020-07-11 22:20:00,9225.99,9232.06,9225.99,9231.96,53.251515
4,2020-07-11 22:21:00,9231.96,9235.00,9231.96,9235.00,22.051639
...,...,...,...,...,...,...
524643,2021-07-11 22:13:00,34464.07,34499.00,34457.49,34462.99,57.726496
524644,2021-07-11 22:14:00,34462.98,34478.60,34448.99,34451.15,33.589879
524645,2021-07-11 22:15:00,34451.14,34451.98,34403.22,34424.54,115.045592
524646,2021-07-11 22:16:00,34424.54,34424.54,34381.83,34381.84,61.389608
524647,2021-07-11 22:17:00,34381.84,34394.53,34359.85,34389.98,84.824510

In [42]:
# SMA, EMA, VWAP 6

for name, f in [("sma", ta.trend.sma_indicator), ("ema", ta.trend.ema_indicator)]:
    for x in [20, 50, 100]:
        df[f"{name}_{x}"] = f(close=df.close, window=x, fillna=True)
for x in [20, 50, 100]:
    df[f"vwap_{x}"] = ta.volume.volume_weighted_average_price(
        close=df.close, high=df.high, low=df.low, fillna=True, volume=df.volume, window=x
    )
for name in ["sma", "ema", "vwap"]:
    for fast, slow in [(20, 50), (20, 100), (50, 100)]:
        data[f"{name}_{fast}_{slow}"] = (
            df[f"{name}_{fast}"] > df[f"{name}_{slow}"]
        ).replace({False: 0, True: 1})

In [43]:
# Awesome 1
data[f"awesome_oscillator"] = (
    ta.momentum.awesome_oscillator(high=df.high, low=df.low, fillna=True) > 0
).replace({False: 0, True: 1})

In [44]:
# KAMA 1 
data[f"awesome_oscillator"] = (
    ta.momentum.kama(close=df.close, fillna=True) > df.close
).replace({False: 0, True: 1})

In [45]:
# PPO 2
ppo = ta.momentum.PercentagePriceOscillator(close=df.close, fillna=True)
data[f"ppo"] = (
    ppo.ppo() > 0
).replace({False: 0, True: 1})
data[f"ppo_hist"] = (
    ppo.ppo_hist() > 0
).replace({False: 0, True: 1})

In [46]:
# PVO 2
pvo = ta.momentum.PercentageVolumeOscillator(volume=df.volume, fillna=True)
data[f"pvo"] = (
    pvo.pvo() > 0
).replace({False: 0, True: 1})
data[f"pvo_hist"] = (
    pvo.pvo_hist() > 0
).replace({False: 0, True: 1})

In [47]:
# RSI 3
for name in ["close", "high", "low"]:
    data[f"rsi_{name}"] = ta.momentum.rsi(close=df[name], fillna=True) / 100

In [48]:
# S_RSI 3
s_rsi = ta.momentum.StochRSIIndicator(close=df.close, fillna=True)
data["srsi"] = s_rsi.stochrsi()
data["srsi_d"] = s_rsi.stochrsi_d()
data["srsi_k"] = s_rsi.stochrsi_k()

In [49]:
# S_RSI 2
s_osc = ta.momentum.StochasticOscillator(close=df.close, high=df.high, low=df.low, fillna=True)
data["stoch"] = s_osc.stoch() / 100
data["stoch_signal"] = s_osc.stoch_signal() / 100

In [75]:
# TSI 1
data[f"tsi"] = (ta.momentum.tsi(close=df.close, fillna=True) + 100) / 200

In [51]:
# Ultim_O 1
data[f"ultimate_o"] = ta.momentum.ultimate_oscillator(
    close=df.close, high=df.high, low=df.low, fillna=True
) / 100

In [74]:
# will 1
data[f"will"] = (ta.momentum.williams_r(
    close=df.close, high=df.high, low=df.low, fillna=True
) + 100) / 100

In [76]:
# CMF 1
data[f"cmf"] = (ta.volume.chaikin_money_flow(
    close=df.close, high=df.high, low=df.low, fillna=True, volume=df.volume
) + 1 ) / 2

In [54]:
# EM 2
ease_movement = ta.volume.EaseOfMovementIndicator(
    high=df.high, low=df.low, fillna=True, volume=df.volume
)
data[f"em"] = (
    ease_movement.ease_of_movement() > 0
).replace({False: 0, True: 1})
data[f"sem"] = (
    ease_movement.sma_ease_of_movement() > 0
).replace({False: 0, True: 1})

In [55]:
# MFI 1
data[f"mfi"] = ta.volume.money_flow_index(
    close=df.close, high=df.high, low=df.low, fillna=True, volume=df.volume
) / 100

In [56]:
# BB 3
bb = ta.volatility.BollingerBands(close=df.close)
data[f"bbh"] = bb.bollinger_hband_indicator()
data[f"bbl"] = bb.bollinger_lband_indicator()
data[f"bbm"] = (
    bb.bollinger_mavg() > df.close
).replace({False: 0, True: 1})

In [57]:
# DC 3
dc = ta.volatility.DonchianChannel(close=df.close, high=df.high, low=df.low)
data[f"dch"] = (
    dc.donchian_channel_hband() < df.close
).replace({False: 0, True: 1})
data[f"dcl"] = (
    dc.donchian_channel_lband() > df.close
).replace({False: 0, True: 1})
data[f"dcm"] = (
    dc.donchian_channel_mband() > df.close
).replace({False: 0, True: 1})

In [58]:
# KC 3
kc = ta.volatility.KeltnerChannel(close=df.close, high=df.high, low=df.low)
data[f"kch"] = kc.keltner_channel_hband_indicator()
data[f"kcl"] = kc.keltner_channel_lband_indicator()
data[f"kcm"] = (
    kc.keltner_channel_mband() > df.close
).replace({False: 0, True: 1})

In [59]:
# ADX 3
adx = ta.trend.ADXIndicator(close=df.close, high=df.high, low=df.low, fillna=True) 
data[f"adx"] = adx.adx() / 100
data[f"adx_neg"] = adx.adx_neg() / 100
data[f"adx_pos"] = adx.adx_pos() / 100

/home/tttienthinh/Documents/Programmation/Scientist/venv/lib/python3.8/site-packages/ta/trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
/home/tttienthinh/Documents/Programmation/Scientist/venv/lib/python3.8/site-packages/ta/trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])

In [77]:
# Aroon 3
aroon = ta.trend.AroonIndicator(close=df.close, fillna=True) 
data[f"aroon_d"] = aroon.aroon_down() / 100
data[f"aroon_u"] = aroon.aroon_up() / 100
data[f"aroon_i"] = (aroon.aroon_indicator() + 100) / 200

In [61]:
# CCI 1
data[f"cci"] = (
    ta.trend.cci(close=df.close, high=df.high, low=df.low, fillna=True) > 0
).replace({False: 0, True: 1})

In [62]:
# DPO 1
data[f"dpo"] = (
    ta.trend.dpo(close=df.close, fillna=True) > 0
).replace({False: 0, True: 1})

In [63]:
# KST 3
kst = ta.trend.KSTIndicator(close=df.close, fillna=True)
data[f"kst"] = (
    kst.kst() > 0
).replace({False: 0, True: 1})
data[f"kst_diff"] = (
    kst.kst_diff() > 0
).replace({False: 0, True: 1})
data[f"kst_sig"] = (
    kst.kst_sig() > 0
).replace({False: 0, True: 1})

In [64]:
# MACD 3
macd = ta.trend.MACD(close=df.close, fillna=True)
data[f"macd"] = (
    macd.macd() > 0
).replace({False: 0, True: 1})
data[f"macd_d"] = (
    macd.macd_diff() > 0
).replace({False: 0, True: 1})
data[f"macd_s"] = (
    macd.macd_signal() > 0
).replace({False: 0, True: 1})

In [65]:
# PSAR
psar = ta.trend.PSARIndicator(close=df.close, high=df.high, low=df.low, fillna=True)
data["psar_d"] = psar.psar_down_indicator()
data["psar_u"] = psar.psar_up_indicator()

In [66]:
# STC 1
data["stc"] = ta.trend.stc(close=df.close, fillna=True) / 100

In [67]:
# trix 1
data["trix"] = (
    ta.trend.trix(close=df.close, fillna=True) > 0
).replace({False: 0, True: 1})

In [68]:
# vortex 1
vortex = ta.trend.VortexIndicator(close=df.close, high=df.high, low=df.low, fillna=True)
data["vortex"] = (
    vortex.vortex_indicator_diff() > 0
).replace({False: 0, True: 1})

In [69]:
data

,sma_20_50,sma_20_100,sma_50_100,ema_20_50,ema_20_100,ema_50_100,vwap_20_50,vwap_20_100,vwap_50_100,awesome_oscillator,...,kst_diff,kst_sig,macd,macd_d,macd_s,psar_d,psar_u,stc,trix,vortex
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.0,0.0,0.000000,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0.0,0.0,0.000000,0,0
2,0,0,0,1,1,1,0,0,0,0,...,1,0,1,1,1,1.0,0.0,0.000000,1,1
3,0,0,0,1,1,1,0,0,0,0,...,1,0,1,1,1,0.0,1.0,0.000000,1,1
4,0,0,0,1,1,1,0,0,0,0,...,1,0,1,1,1,0.0,0.0,0.000000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524643,1,1,1,1,1,1,1,1,1,1,...,0,1,1,0,1,0.0,0.0,0.000875,1,0
524644,1,1,1,1,1,1,1,1,1,1,...,0,1,1,0,1,0.0,0.0,0.000438,1,0
524645,1,1,1,1,1,1,1,1,1,1,...,0,1,1,0,1,0.0,0.0,0.000219,1,0
524646,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,1,0.0,0.0,0.000109,1,0
524647,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,1,0.0,0.0,0.000055,1,0

In [82]:
data.to_csv("data_creation.csv", index=False)